### PR TITLE
Addition of Geosilhouettes

### PR DESCRIPTION
**Pull request by AnGWar26**
Thought it would be best if I gave you the opportunity to comment on this as I work @knaaptime.

Todo:
- [x] All this code is held together by running `gdf.fillna(0)` before running the clusterer, need to find solution that handles NaN values and keeps the index the same length as the dataframe.
- [x] Handle input when an aspatial model is passed to a spatial diagnostic
	- Currently throws what might be a cryptic error to most users `'NoneType' object has no attribute 'sparse'`, referring to the absence of a W object
- Figure out why these functions return 3 axes when I think they should be returning 2. The third is `dtype=object`

Updated 8/19

### CODE REVIEW

**Comment by knaaptime** [comment]
cool, lets talk about this a bit during the meeting on tuesday. It'll be a little easier to describe what i mean about stashing the index so we dont have to fillna

Also i think it would be better to switch the ordering of the plotting nomenclature, e.g. instead of `***_plot(...)`, i think it would be better to do `plot_***(...)`

**Comment by knaaptime** [comment]
>Handle input when an aspatial model is passed to a spatial diagnostic
Currently throws what might be a cryptic error to most users 'NoneType' object has no attribute 'sparse', referring to the absence of a W object

one thing we could do is add a little metadata attribute to the ModelResults class that stores whether the model is spatial or aspatial. That way we can add a simple check if users pass the wrong type of model to the wrong diagnostic

**Comment by knaaptime** [comment]
awesome! looks like this has everything we talked about yesterday. Everything working as expected?

**Comment by AnGWar26** [comment]
As far as I can tell everything works as expected, and at this point I would designate this ready for review. However, this is such a big PR (+500 lines), and with your understanding of these statistics being better than mine, I would encourage you to test it out yourself before merging.

Let me know if these needs anymore changes.

**Pull request merged**
