### PR TITLE
start harmonization module

### PR DESCRIPTION
**Pull request by knaaptime**
this is a quick and dirty start to the harmonization module. Currently, all it does is shade the harmonize function from tobler and make it available as a method on the Community class. 

We now have ncld rasters for different years as well as 2000 and 2010 block-level census data in the quilt bucket (i've got housing and population counts for 2010 but no attributes yet for 2000) so there are lots of ways to improve this quickly

### CODE REVIEW

**Comment by renanxcortes** [comment]
> We now have ncld rasters for different years as well as 2000 and 2010 block-level census data in the quilt bucket (i've got housing and population counts for 2010 but no attributes yet for 2000) so there are lots of ways to improve this quickly

hm.. interesting, but if this is the case, I think we need to tweak the harmonize's tobler function since I believe it only presupposes one NLCD raster.

ps.: I think that "`numpy` not found" issue with the travis build is happening again.

**Comment by knaaptime** [comment]
> hm.. interesting, but if this is the case, I think we need to tweak the harmonize's tobler function since I believe it only presupposes one NLCD raster.

I just meant that we have them available internally so that we can use convenience methods for providing the paths and the users dont need to download the data manually (then they can choose which raster is more appropriate for their problem)

> ps.: I think that "numpy not found" issue with the travis build is happening again.

yeah, the tests are broken until the [quilt](https://github.com/conda-forge/staged-recipes/pull/9000) conda-forge recipe gets merged

**Comment by knaaptime** [comment]
the second commit here uses the `if __name__ == "__main__"  convention to mask the dash app and the utilities that need internet connection to (1) reduce memory overhead and (2) make sure that geosnap still works without an internet connection

**Comment by knaaptime** [comment]
one thing to note is that we're still going to run into a CI build error even when quilt is added to conda forge because we now import tobler, which has unspecified dependencies (shap, xgboost) at the moment

**Comment by renanxcortes** [comment]
> one thing to note is that we're still going to run into a CI build error even when quilt is added to conda forge because we now import tobler, which has unspecified dependencies (shap, xgboost) at the moment

Good catch! Will fix that.

**Pull request merged**
