### PR TITLE
better handling of cluster internals

### PR DESCRIPTION
**Pull request by knaaptime**
this PR makes a few improvements to the clustering internals

- it uses multiindices rather than creating several hacky columns then dropping them
- it adds a new `scaler` argument that accepts any `sklearn.preprocessing` class to scale inputs
- more flexible handling of spatial weights, including allowing users to provide their own (i.e. allow distance-based weights for algos that can support them)

### CODE REVIEW

**Comment by knaaptime** [comment]
these tests are passing now

**Comment by renanxcortes** [comment]
I think in the build is raising a `FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/spatialucr/geosnap/ltdb_sample.zip'` is this expected?

**Comment by knaaptime** [comment]
i'm not sure why, but it's because the branch doesnt have the environment variables set or something. You [can see](https://github.com/knaaptime/geosnap/runs/194831184) that it passes on my fork

**Comment by knaaptime** [comment]
(if it's merged, the tests will pass on spatialucr/master)

**Comment by renanxcortes** [comment]
> i'm not sure why, but it's because the branch doesnt have the environment variables set or something. You [can see](https://github.com/knaaptime/geosnap/runs/194831184) that it passes on my fork

yep, I see that.... weird

**Comment by renanxcortes** [comment]
> (if it's merged, the tests will pass on spatialucr/master)

Ok, I took a quick look at the code but, most importantly, read the bullet points of the PR and it is fine to me.

**Pull request merged**
