### PR TITLE
assert check for id_var in transition

### PR DESCRIPTION
**Pull request by AnGWar26**
Fixes issue #278
image

### CODE REVIEW

**Comment by knaaptime** [comment]
resolves #278

**Comment by knaaptime** [comment]
I'm +1 on this, though not sure why the windows tests are failing. It has something to do with matplotlib's fontmanager

**Comment by AnGWar26** [comment]
This is weird. I just ran this test on my machine:

`pytest -v  geosnap/tests/test_plots.py`

And got an all clear:

```
platform linux -- Python 3.8.8, pytest-6.2.3, py-1.10.0, pluggy-0.13.1 -- /home/andrew/anaconda3/envs/geosnap/bin/python
cachedir: .pytest_cache
rootdir: /home/andrew/Projects/geosnap
plugins: dash-1.19.0, anyio-2.2.0
collected 9 items                                                                                                    

geosnap/tests/test_plots.py::test_cont_timeseries PASSED                                                       [ 11%]
geosnap/tests/test_plots.py::test_cat_timeseries PASSED                                                        [ 22%]
geosnap/tests/test_plots.py::test_heatmaps PASSED                                                              [ 33%]
geosnap/tests/test_plots.py::test_graphs SKIPPED (pygraphviz couldn't be imported.)                            [ 44%]
geosnap/tests/test_plots.py::test_animation PASSED                                                             [ 55%]
geosnap/tests/test_plots.py::test_boundary_silplot PASSED                                                      [ 66%]
geosnap/tests/test_plots.py::test_path_silplot PASSED                                                          [ 77%]
geosnap/tests/test_plots.py::test_next_label_plot PASSED                                                       [ 88%]
geosnap/tests/test_plots.py::test_silmap_plot PASSED                                                           [100%]
```

**Comment by knaaptime** [comment]
i think the root of the problem is an incompatibility between the latest versions of matplotlib and proplot https://github.com/lukelbd/proplot/issues/248

**Comment by AnGWar26** [comment]
I just confirmed this on my machine by updating `matplotlib` and got the same error described in that issue.

We could either:

- Pin `matplotlib` to `3.3.4` for now
- Drop `proplot` and rewrite pieces of  `plot_timeseries` that depend on it.
- Pin `matplotlib` to 3.3.4 for now and rewrite `plot_timeseries` if `proplot` isn't fixed.

**Pull request merged**
