### PR TITLE
refactor

### PR DESCRIPTION
**Pull request by knaaptime**
#### update - changes in this pr:

refactor
 - renames the `data` module to `io`
 - renames the `data_store` to `datasets`
 - moves the `Community` class and `datasets` to the top-level
 - adds a `models` attribute to the Community that stores fitted cluster etc models

test suite
 - add tests for example notebooks
 - dont download data for tar builds
 - restructure to avoid external datasets when possible (allow testing on forks)

docs
 - update api docs for refactor
 - update makefile to keep figs and remove more junk on cleanup
 - update readme

misc
 - fail informatively on missing rasters
 - simplify fips filter
 - expose missing `store_blocks` functions
 - remove old readthedocs config

### CODE REVIEW

**Comment by knaaptime** [comment]
because i dont want them to show up in tab completion

**Comment by knaaptime** [comment]
(otherwise e.g. you'd get both `geosnap.community` and `geosnap.Community` when you tab)

**Comment by knaaptime** [comment]
i want to trigger a travis build, so i'll do the docs in a separate PR

**Comment by knaaptime** [comment]
tests pass locally but i cant get the build to trigger on travis...

**Comment by weikang9009** [comment]
.travis.yml https://github.com/knaaptime/geosnap/blob/refactor_data/.travis.yml#L39 also needs to be changed to accommodate the API change

**Comment by weikang9009** [comment]
The travis CI seems to have not been triggered for the past three months. The last CI build on the master branch was from PR https://github.com/spatialucr/geosnap/pull/130

**Comment by knaaptime** [comment]
good catch. Looks like @suhanmappingideas got one to trigger from the `vizsu` branch and that seems to have gotten things moving. how strange

**Comment by knaaptime** [comment]
I reworked the tests and CI config so that as long as you have the LTDB and NCDB environment variables set, tests should pass on forks

(everything is passing on mine) this should be ready to go

**Pull request merged**
